### ISSUE TITLE
Uncaught (in promise) Error

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [murat-mehmet/mobx-observable-promise#6]
```
Uncaught (in promise) Error
    at ObservablePromise.eval [as _action] (App.js? [sm]:6)
    at eval (ObservablePromise.js:332)
    at new Promise (<anonymous>)
    at ObservablePromise.execute (ObservablePromise.js:331)
    at onClick (App.js? [sm]:12)
```
More stack calls excluded.

Code to reproduce error:
```jsx
import { ObservablePromise } from "mobx-observable-promise";
import { observer } from "mobx-react-lite";

const promise = new ObservablePromise(async () => {
  throw new Error();
});

export default observer(function App() {
  return (
    <>
      <button onClick={() => promise.execute()}>Execute</button>
      <br />
      {promise.isError ? "Is error" : "no error"}
    </>
  );
});
```

Link to Code Sandbox: https://codesandbox.io/s/mobx-observable-promise-bug-6cxlq?file=/src/App.js:0-388

**Comment by murat-mehmet** [comment]
Hey there,

You simply need to catch error. Try `promise.execute().catch()`

**Comment by ChocolateLoverRaj** [comment]
@murat-mehmet I did that and it worked. This was just unexpected because I assumed the `ObservablePromise` would handle all promise rejections.

**Comment by murat-mehmet** [comment]
Thanks for your feedback, this sure needs to go in documentation.

Not catching rejections internally gives us possibility to use ObservablePromise like a regular Promise.
```
promise.execute()
  .then(result => { /* do somthing with result */ })
  .catch(e => { /* do something with error */ })
```
`then` and `catch` in `ObservablePromise` are just shortcuts to access the actual promise which can be accessed by `promise` field. The upper example is a shortcut for:
```
promise.execute()
  .promise
  .then(result => { /* do somthing with result */ })
  .catch(e => { /* do something with error */ })
```

Also `promise.execute().catch()` is equal to:
```
promise.execute()
  .promise
  .catch(e => null)
```

So both you can chain promises one after another and access their state reactively in `render()`.
