### ISSUE TITLE
Wierd version publishing

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [murat-mehmet/mobx-observable-promise#7]
`0.4.12` is the version that gets downloaded by default, because it was the last one published.
![image](https://user-images.githubusercontent.com/52586855/146648957-09a0fcc4-3a07-4783-aa31-a186b7304ac1.png)

**Comment by murat-mehmet** [comment]
Oops, thanks for the heads-up. v0.4 is mobx-5 compatible and v0.5 is mobx-6 compatible versions. So it was my bad to lastly release update to the mobx-5 compatible version. To fix the issue, I just published a new version and will keep this in mind at future releases.

**Comment by ChocolateLoverRaj** [comment]
@murat-mehmet What if you made `1.x.x` for mobx 5 and `2.x.x` for mobx 6?

**Comment by murat-mehmet** [comment]
Well, I'm planning to drop support for mobx 5 soon. I'm just waiting for a complete version to increase to `1.0`. Especially documentation requires a lot of time and it's far from complete. There are `CallPromise`, `InfiniteObservablePromise`, `InfiniteCallPromise`, `CachedCallPromise`, `CachedObservablePromise` and `FetchPromise` classes in this library which are inherited from `ObservablePromise` and have a lot of benefits. I am not a very good doc writer but will invest some time in the future to create a nice documentation with gitbook.

**Comment by murat-mehmet** [comment]
Closing this, thanks for feedback.
